/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 64baee7c07c34f4d8b4f0da017008b76)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "SyncedState";
	}
	interface Env {
		ASSETS: Fetcher;
		SYNCED_STATE: DurableObjectNamespace<import("./src/worker").SyncedState>;
	}
}
interface Env extends Cloudflare.Env {}
